AllCops:
  NewCops: enable
  SuggestExtensions: false
  UseCache: true

Layout/LineLength:
  Max: 100

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses
  IgnoreMacros: false
  AllowedMethods:
    - require
    - require_relative
    - it
    - xit
    - describe
    - xdescribe
    - to

Style/NumericPredicate:
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/ZeroLengthPredicate:
  Enabled: false
